// Procurement status transition rules (SOAR Appendix C).
// Centralising this in one place means every route enforces the same
// legal workflow ordering instead of re-implementing checks ad hoc.

const TRANSITIONS = {
  DRAFT: ['INTERNAL_REVIEW', 'CANCELLED'],
  INTERNAL_REVIEW: ['APPROVED_FOR_PUBLICATION', 'DRAFT', 'CANCELLED'],
  APPROVED_FOR_PUBLICATION: ['PUBLISHED', 'CANCELLED'],
  PUBLISHED: ['CLARIFICATION_PERIOD', 'SUBMISSION_OPEN', 'CANCELLED'],
  CLARIFICATION_PERIOD: ['SUBMISSION_OPEN', 'CANCELLED'],
  SUBMISSION_OPEN: ['CLOSED', 'CANCELLED'],
  CLOSED: ['TECHNICAL_OPENING', 'CANCELLED'],
  TECHNICAL_OPENING: ['COMPLIANCE_EVALUATION'],
  COMPLIANCE_EVALUATION: ['TECHNICAL_EVALUATION', 'CANCELLED'],
  TECHNICAL_EVALUATION: ['TECHNICAL_OUTCOME_APPROVED', 'CANCELLED'],
  TECHNICAL_OUTCOME_APPROVED: ['FINANCIAL_OPENING'],
  FINANCIAL_OPENING: ['FINANCIAL_EVALUATION'],
  FINANCIAL_EVALUATION: ['AWARD_PENDING_APPROVAL', 'CANCELLED'],
  AWARD_PENDING_APPROVAL: ['AWARD_PUBLISHED', 'CANCELLED'],
  AWARD_PUBLISHED: ['COOLING_OFF'],
  COOLING_OFF: ['COMPLAINT_HOLD', 'READY_FOR_CONTRACT'],
  COMPLAINT_HOLD: ['READY_FOR_CONTRACT', 'CANCELLED'],
  READY_FOR_CONTRACT: ['ARCHIVED'],
  CANCELLED: ['ARCHIVED'],
  ARCHIVED: [],
};

function canTransition(from, to) {
  return (TRANSITIONS[from] || []).includes(to);
}

module.exports = { TRANSITIONS, canTransition };
